config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "game#index"

  get    "/select" => "characters#select"
  patch "/characters/auto_save" => 'characters#auto_save'
  #patch  "/characters" => "characters#selection"
  get "/game" => 'characters#game'
  get "instructions"=> 'characters#instructions'
  get "about" => 'characters#about'



  resources :characters, only: [:create, :game, :new, :update, :edit]

  resources :items, only: [:create]

  delete "/items/use" => 'items#use_item'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  has_many :items

  validates :name, uniqueness: true, length: {minimum: 3, maximum: 10}
  belongs_to :party, required: false
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :character
end

app/models/party.rb
class Party < ApplicationRecord
  has_many :characters
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :characters
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :check_character, only: [:game]
  before_action :set_character_name, only: :game
  before_action :authenticate_user!, except: [:index, :show, :instructions, :about, :update, :select]


  def new
    @character = current_user.characters.build
  end

  def create
    @character = current_user.characters.build(character_params)
    @character.attack += 1
    @character.defense += 1
    @character.max_health += 1
    @character.attack /= 1.5;
    @character.defense /= 2;
    @character.max_health *= 3;
    @character.health = @character.max_health;
    if @character.save
      binding.pry
      flash[:notice] = "\"#{@character.name}\" has been successfully created."
      session[:character_id] = @character.id
      3.times { @character.items << Item.new(name: "potion") }
    else
      flash[:notice] = @character.errors.full_messages.join("\n")
    end
    redirect_to "/"
  end

  def update
    # @character1 = Character.find_by(id: session[:character_id])
    # @character1.update_attribute :character_id, current_user.character.id
    # @character1.save
    params.permit(:id)
    @character1 = Character.find(params[:character][:id])
    session[:character_id] = @character1.id
    flash[:notice] = "You have changed your character to\"#{@character1.name}\"."
    redirect_to "/"
  end

  def auto_save
    character = Character.find_by(id: session[:character_id])
    params.permit(:pos_x)
    params.permit(:pos_y)
    params.permit(:max_health)
    params.permit(:attack)
    params.permit(:xp)
    params.permit(:level)
    params.permit(:defense)
    params.permit(:health)
    character.pos_x = params[:pos_x].to_i
    character.pos_y = params[:pos_y].to_i
    character.max_health = params[:max_health].to_i
    character.attack = params[:attack].to_i
    character.XP = params[:xp].to_i
    character.level = params[:level].to_i
    character.defense = params[:defense].to_i
    character.health = params[:health].to_i
    character.save
  end

  def edit
  end

  def select
     @character1=current_user.characters.all
  end

  def game

  end

  def instructions
  end

  def about
  end

  private

    def check_user
      if session[:user_id].nil?
        flash[:notice] = "Please login or create a new account."
        redirect_to "/users/register"
      end
    end

    def check_character
      if session[:character_id].nil?
        flash[:notice] = "Please create a character."
        redirect_to "/"
      end
    end

    def set_character_name
      @character = Character.find_by(id: session[:character_id])

    end
      private

  def character_params
    params.require(:character).permit(:name, :location, :user_id, :party_id, :attack, :health, :XP, :defense, :max_health)
  end
end

app/controllers/concerns/game_controller.rb
class GameController < ApplicationController
	
	def index
	end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    if session[:character_id]
      params.permit(:item_name)
      Item.create(name: params[:item_name], character_id: session[:character_id])
    end
  end

  def use_item
    if session[:character_id]
      params.permit(:item_name)
      Item.where(name: params[:item_name], character_id: session[:character_id]).first.destroy
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/about.html.erb
<%= video_tag "landscape.webm", id:"video-background", autoplay: true, loop: true %>
<div class=".container-fluid">
 <div class="row">
  <div class="col-xs-1">
  </div>
 <div class="col-xs-7">
<%=image_tag "newwood.png", id: "wood1", height: 600, width: 950 %>
  <div class="homescreentext">
  <h1>ABOUT</h1>
   <h10>Boss Triangles is a  massively multiplayer online game or MMO.  You are required to explore our map where you will encounter random battles with  gnarley adversaries !  The objective of Boss Triangles is to fight/defeat enemies, collect items and level up in the process.  We allow a large numbers of players to  simultaneously interact with each other during gameplay(websockets are sick!!)
  Boss Triangles was built entirely with Javascript and Ruby on Rails(no gaming engines of course).  All of our characters are also hand drawn, which is pretty BOSS!!</h10>
<h2>Team</h2>
<h10>Harrison Zandri, Lloyd Clave, Patrick Guerrier, Taiki Kosugi, Adam for music!</h10>
          </div>
      </div>
      </div>
    </div>

app/views/characters/game.html.erb
<!-- <div style="position:absolute;width:300px;height:200px;left:0;top:20px;background-color:red;z-index:1"> This is the menu
  </div> -->
<canvas style="z-index:-1" id="game_screen" width="800" height="600"></canvas>

<!-- <script src="http://d3js.org/d3.v3.min.js"></script> -->
<!-- <script src="../../assets/javascripts/d3.js"></script> -->
<script>
// LOADING SCREEN
// TODO: ajax call to receive your_char information
// REMOVE LOADING SCREEN
  var scheme = "ws://";
  <% if ENV["ENCRYPTED_WEBSOCKET"] == "true" %>
    scheme = "wss://";
  <% end %>
  setUpWebsocket(scheme);
  $('document').ready(function(){
    setAutoLogout(); //logout when user exits browser or tab
    allowInput(); // key listeners to keyboard
    allowClick(); // click listener
    fieldMusic.volume = 0.8;
    fieldMusic.play();
    setInterval(fieldMusicLoop, 900);


    // Main logic
    setCharacterUpdate('<%= @character.name %>', <%= @character.pos_x %>, <%= @character.pos_y %>, <%= @character.attack %>, <%= @character.health %>, <%= @character.XP %>, <%= @character.defense %>, <%= @character.max_health %>, <%= @character.level %> ); // passes player position and player identity data to the server
    <% @character.items.each do |item| %>
      your_char.inventory.push('<%= item.name %>');
    <% end %>
    setCanvasDrawingUpdate(); //redraws canvas 30 fps5
    setAutoSave();
  });
</script>

<div id="chat-box">
  <div id="chat-display">
    <ul id="chat-message-list" style="list-style-type: none;">
    </ul>
    <div id="bottom"></div>
  </div>
  <input text="text" name="chat_window" style="width:500px;">
  <button id="chat-submit">Submit</button>
</div>

<div id="cool-triangle">
	<img src=<%= asset_path "triangle_01.gif" %> alt="Cool triangle" height="180" width="280">
</div>

<div id="information_window">

  <div id="playerName">
    <div class="field">
      Player Name
    </div>
    <div class="value">
    </div>
  </div>

  <div id="level">
    <div class="field">
      Level
    </div>
    <div class="value">
    </div>
  </div>

  <div id="health">
    <div class="field">
      Health
    </div>
    <div class="value">
    </div>
  </div>

  <div id="experience">
    <div class="field">
      Experience
    </div>
    <div class="value">
    </div>
  </div>

  <div id="partyMembers">
	  <div class="field">
	    Party Members
	  </div>
	  <div class="value">
	  </div>
	</div>

	<div id="items">
	  <div class="field">
	    Items
	  </div>
	  <div class="value">
	  </div>
	</div>

	<div id="control">
	  <div class="value">
	  </div>
	</div>

</div>

app/views/characters/instructions.html.erb
<%= video_tag "landscape.webm", id:"video-background", autoplay: true, loop: true %>
<div class="parent">
 <div class="col-md-7 col-md-offset-2">
  <div class="row">
  <%=image_tag "newwood.png", id: "wood", height: 400, width: 700 %>
  <div class="homescreentext">
   <h1>How to play:<h1>
<h10>1) Create a character</h10> <br>
<h10>2) Enter game</h10> <br>
<h10>3) Walk around map while randomly fighting enemies </h10><br>
<h10>4) Level up while collecting items from defeating enemies</h10><br>
<h10>4) BE A BOSS!!!</h10>
          </div>
      </div>
      </div>
    </div>

app/views/characters/new.html.erb
<%= video_tag "abstract.webm", id:"video-background", autoplay: true, loop: true %>
 <h1>CREATE CHARACTER</h1>
<br>
<br>
<br>
<br>
<div class="col-md-4 col-md-offset-2">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
      <div id="the_slider">

<h7>Character Attributes</h7><br><br>
<%= form_for @character do |create| %>

  <div class="charinput">
  <%= create.label :name %>
  <%= create.text_field :name %>
 </div>

  <%= create.label :attack %><br>
    <div id="slider" class="slider1"></div>
  <%= create.hidden_field :attack %>


  <%= create.label :defense %><br>
  <div id="slider" class="slider2"></div><div id="total"></div>
  <%= create.hidden_field :defense %>

  <%= create.label :max_health %><br>
  <div id="slider" class="slider3"></div>
  <%= create.hidden_field :max_health %>
<br>

  <%= create.submit %>
<% end %>
       </div>
      </div>
    </div>
  </div>
</div>
  <br>
<br>
<div class="text-center col-md-5 col-md-offset-4.4">
  <%=image_tag("knight_south01.png", height: 400, width: 300)%>
    </div>
  </div>
</div>

<script type="text/javascript">
  $('.slider1').slider({
        min: 0,
        max: 100,
    slide: function (ev, ui) {
        var total = ui.value;
        $('#slider').not(this).each(function () {
            total += $(this).slider('value');
        })
        // if (total > 100) {
        //     return false;
        //   }
    },
    change: function(ev, ui0) {
      $('input#character_attack').val(ui0.value);

    }
});

  $('.slider2').slider({
        min: 0,
        max: 100,
    slide: function (ev, ui) {
        var total = ui.value;
        $('#slider').not(this).each(function () {
            total += $(this).slider('value');
        })
        // if (total > 100) {
        //     return false;
        //   }
    },
    change: function(ev, ui0) {
      console.log("changed");
      $('input#character_defense').val(ui0.value);
    }
});

   $('.slider3').slider({
        min: 0,
        max: 100,
    slide: function (ev, ui) {
        var total = ui.value;
        $('#slider').not(this).each(function () {
            total += $(this).slider('value');
        })
        // if (total > 100) {
        //     return false;
        //   }
    },
    change: function(ev, ui0) {
      $('input#character_max_health').val(ui0.value);
    }

});
   var correctBars = function() {
    var total = 0;
    total += $(".slider1").slider('value');
    total += $(".slider2").slider('value');
    if(total > 100) {
      $(".slider2").slider('value', 100 - $(".slider1").slider('value'));
      total = 0;
      total += $(".slider1").slider('value');
      total += $(".slider2").slider('value');
    }
    total += $(".slider3").slider('value');
    if(total > 100) {
      $(".slider3").slider('value', 100 - ($(".slider1").slider('value') + $(".slider2").slider('value')));
    }
    console.log(total);
   }
   setInterval(correctBars, 33);

</script>

app/views/characters/select.html.erb
<%= video_tag "landscape.webm", id:"video-background", autoplay: true, loop: true %>
 		<h1>SELECT CHARACTER</h1>
 		<div class=".container-fluid">
    <div class="col-xs-1">
    </div>

    <div class="col-xs-9">
      <div class="row">

		<%=image_tag "newwood.png", id: "wood2", height: 450, width: 900 %>
		</div>
    </div>
        </div>
					<br>
				<br>
			<br>
		<br>
	<br>
<br>
  <div align="center">
<div class="text-center col-md-5 col-md-offset-4">
  <br>
  <br>
  <br>
<br>

	<%=image_tag("knight_south01.png", height: 350, width: 300)%>
		<div class="col-md-5 ">
			<% if @character1.exists? %>
			<div id="content">
    			<div id="left">
					<%@character1.each do |character|%>
  						<h10><%=character.name%></h10><br>
  						<%= form_for character, method: :PATCH, url: "/characters/update" do |f| %>
    					<%= f.hidden_field :id, :value => character.id %>
    					<%= f.submit "Select Character" %>
  							<% end %>
   						<% end %>
     			</div>
     		</div>
        <br>
         <br>
          <br>
  						<%else%>
  							<h1>HURRY UP AND MAKE A CHARACTER</h1>
  								<%= link_to('Create Character', new_character_path) %>
						<% end %>
	</div>
</div>

app/views/game/index.html.erb
<%= video_tag "landscape.webm", id:"video-background", autoplay: true, loop: true %>

<div class=".container">
    <div class="row">
 <div class="col-xs-9">
 </div>
  <div align="center">

  <%=image_tag "newwood.png", id: "wood", height: 500, width: 950 %>
</div>
  <div class="homescreentext">
    <h6 class="font-effect-3d">WELCOME TO BOSS TRIANGLES</h6>
      <div id="homepage_links"%>
      <span class="font-effect-3d-float"><%= link_to('How to play', instructions_path)%></span>
      <% if user_signed_in? && current_user.characters %><br>
       <span class="font-effect-3d-float"> <%= link_to('Select Character', select_path) %></span><br>
        <span class="font-effect-3d-float"><%= link_to('Create Character', new_character_path) %></span><br>
        <span class="font-effect-3d-float"><%= link_to('Start Game', game_path)%></span><br>
        <%else%><br>
        <h8 class="font-effect-fire-animation">YOU ARE NOT WORTHY</h8> <br>
          <% end %>
          </div>
      </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The MMO</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application' %>  
    <link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light|Passion+One|family=Black+Ops+One|Luckiest+Guy|Sonsie+One|Shojumaru&effect=3d|3d-float|anaglyph|brick-sign|canvas-print|
            crackle|decaying|destruction|distressed|distressed-wood|emboss|fire|fire-animation|fragile|grass|ice|mitosis|neon|outline|putting-green|
            scuffed-steel|shadow-multiple|splintered|static|stonewash|vintage|wallpaper' 
            rel='stylesheet' type='text/css'>
  </head>
  	<nav class="hidenav">
		<div class ="container">
			<div class="navbar-brand">
			<%= link_to "Boss Triangles", root_path %>
			</div>
			<% if user_signed_in? %>
				<ul class="nav navbar-nav navbar-right">
					<li> 
					<%=link_to "Account", edit_user_registration_path %>
					</li>
					<li>
					<%= link_to('Logout', destroy_user_session_path, :method => :delete)%>
					</li>
					<li>
					<%= link_to "About", about_path %>
					</li>
				</ul>
			<% else %>
				<ul class="nav navbar-nav navbar-right">
        			<li>
        			<%= link_to('Sign In', new_user_session_path)%>
        			</li>
        			<li>
  					<%= link_to "Sign Up", new_user_registration_path %>
  					</li>
  					<li>
					<%= link_to "About", about_path %>
					</li>
        		</ul>
        	<%end%>
		</div>
	</nav>
	<div class ="container">
		<% flash.each do |name, msg| %>
			<%= content_tag :div, msg, class: "alert alert-info" %>
		<%end%>
	</div>
	<body>
    	<%= yield %>
  </body>
</html>